/*
 * Pixop API
 *  The Pixop API provides a comprehensive RESTful interface for interacting with the Pixop Platform. It allows users to manage API keys, projects, videos, and more.  The Pixop Platform offers video processing features such as upscaling, format conversion, and compression. It uses AI-driven algorithms to optimize video quality, reduce file sizes, and improve playback performance.  **Quick Start Guide** - Explore the [Pixop API Documentation](https://docs.pixop.com/reference/) to familiarize yourself with the API's capabilities.  **Required Headers** Include the following headers in all API requests: - `Accept`: `application/json` - `Content-Type`: `application/json` - `X-API-Key`: Your API key for authentication (e.g., `X-API-Key: <your-api-key>`).     **Note:** API key management endpoints that use Basic Authentication do not require the `X-API-Key` header.  **Rate Limits** All endpoints, except those related to API key management, enforce rate limits. Response headers provide the following rate limit details: - `X-RateLimit-Limit`: The maximum number of requests allowed per minute. - `X-RateLimit-Remaining`: The number of requests remaining in the current rate limit window. - `X-RateLimit-Reset`: The number of seconds until the current rate limit window resets. 
 *
 * The version of the OpenAPI document: 2.1.0
 * Contact: api@pixop.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.pixop.api.sdk.model.dto;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import com.pixop.api.sdk.model.dto.CreditsUsageTotalsByCategory;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;
import java.io.UnsupportedEncodingException;
import java.net.URLEncoder;
import java.util.StringJoiner;

/**
 * A summary of Pixop Credits usage totals categorized by type, including overall totals.
 */
@JsonPropertyOrder({
  CreditsUsageTotals.JSON_PROPERTY_TOTALS_FOR_ALL_CATEGORIES,
  CreditsUsageTotals.JSON_PROPERTY_TOTALS_BY_CATEGORY
})
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2026-08-27T09:51:59.238161103Z[UTC]", comments = "Generator version: 7.15.0")
public class CreditsUsageTotals {
  public static final String JSON_PROPERTY_TOTALS_FOR_ALL_CATEGORIES = "totalsForAllCategories";
  @javax.annotation.Nullable
  private CreditsUsageTotalsByCategory totalsForAllCategories;

  public static final String JSON_PROPERTY_TOTALS_BY_CATEGORY = "totalsByCategory";
  @javax.annotation.Nullable
  private List<CreditsUsageTotalsByCategory> totalsByCategory = new ArrayList<>();

  public CreditsUsageTotals() {
  }
  /**
   * Constructor with only readonly parameters
   */
  @JsonCreator
  public CreditsUsageTotals(
    @JsonProperty(JSON_PROPERTY_TOTALS_FOR_ALL_CATEGORIES) CreditsUsageTotalsByCategory totalsForAllCategories
  ) {
    this();
    this.totalsForAllCategories = totalsForAllCategories;
  }

  /**
   * The aggregate usage totals for all categories.
   * @return totalsForAllCategories
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_TOTALS_FOR_ALL_CATEGORIES)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public CreditsUsageTotalsByCategory getTotalsForAllCategories() {
    return totalsForAllCategories;
  }



  public CreditsUsageTotals totalsByCategory(@javax.annotation.Nullable List<CreditsUsageTotalsByCategory> totalsByCategory) {
    
    this.totalsByCategory = totalsByCategory;
    return this;
  }

  public CreditsUsageTotals addTotalsByCategoryItem(CreditsUsageTotalsByCategory totalsByCategoryItem) {
    if (this.totalsByCategory == null) {
      this.totalsByCategory = new ArrayList<>();
    }
    this.totalsByCategory.add(totalsByCategoryItem);
    return this;
  }

  /**
   * The list of usage totals grouped by category.
   * @return totalsByCategory
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_TOTALS_BY_CATEGORY)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public List<CreditsUsageTotalsByCategory> getTotalsByCategory() {
    return totalsByCategory;
  }


  @JsonProperty(JSON_PROPERTY_TOTALS_BY_CATEGORY)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setTotalsByCategory(@javax.annotation.Nullable List<CreditsUsageTotalsByCategory> totalsByCategory) {
    this.totalsByCategory = totalsByCategory;
  }

  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    CreditsUsageTotals creditsUsageTotals = (CreditsUsageTotals) o;
    return Objects.equals(this.totalsForAllCategories, creditsUsageTotals.totalsForAllCategories) &&
        Objects.equals(this.totalsByCategory, creditsUsageTotals.totalsByCategory);
  }

  @Override
  public int hashCode() {
    return Objects.hash(totalsForAllCategories, totalsByCategory);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class CreditsUsageTotals {\n");
    sb.append("    totalsForAllCategories: ").append(toIndentedString(totalsForAllCategories)).append("\n");
    sb.append("    totalsByCategory: ").append(toIndentedString(totalsByCategory)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

  /**
   * Convert the instance into URL query string.
   *
   * @return URL query string
   */
  public String toUrlQueryString() {
    return toUrlQueryString(null);
  }

  /**
   * Convert the instance into URL query string.
   *
   * @param prefix prefix of the query string
   * @return URL query string
   */
  public String toUrlQueryString(String prefix) {
    String suffix = "";
    String containerSuffix = "";
    String containerPrefix = "";
    if (prefix == null) {
      // style=form, explode=true, e.g. /pet?name=cat&type=manx
      prefix = "";
    } else {
      // deepObject style e.g. /pet?id[name]=cat&id[type]=manx
      prefix = prefix + "[";
      suffix = "]";
      containerSuffix = "]";
      containerPrefix = "[";
    }

    StringJoiner joiner = new StringJoiner("&");

    // add `totalsForAllCategories` to the URL query string
    if (getTotalsForAllCategories() != null) {
      joiner.add(getTotalsForAllCategories().toUrlQueryString(prefix + "totalsForAllCategories" + suffix));
    }

    // add `totalsByCategory` to the URL query string
    if (getTotalsByCategory() != null) {
      for (int i = 0; i < getTotalsByCategory().size(); i++) {
        if (getTotalsByCategory().get(i) != null) {
          joiner.add(getTotalsByCategory().get(i).toUrlQueryString(String.format("%stotalsByCategory%s%s", prefix, suffix,
              "".equals(suffix) ? "" : String.format("%s%d%s", containerPrefix, i, containerSuffix))));
        }
      }
    }

    return joiner.toString();
  }

}

