/*
 * Pixop API
 *  The Pixop API provides a comprehensive RESTful interface for interacting with the Pixop Platform. It allows users to manage API keys, projects, videos, and more.  The Pixop Platform offers video processing features such as upscaling, format conversion, and compression. It uses AI-driven algorithms to optimize video quality, reduce file sizes, and improve playback performance.  **Quick Start Guide** - Explore the [Pixop API Documentation](https://docs.pixop.com/reference/) to familiarize yourself with the API's capabilities.  **Required Headers** Include the following headers in all API requests: - `Accept`: `application/json` - `Content-Type`: `application/json` - `X-API-Key`: Your API key for authentication (e.g., `X-API-Key: <your-api-key>`).     **Note:** API key management endpoints that use Basic Authentication do not require the `X-API-Key` header.  **Rate Limits** All endpoints, except those related to API key management, enforce rate limits. Response headers provide the following rate limit details: - `X-RateLimit-Limit`: The maximum number of requests allowed per minute. - `X-RateLimit-Remaining`: The number of requests remaining in the current rate limit window. - `X-RateLimit-Reset`: The number of seconds until the current rate limit window resets. 
 *
 * The version of the OpenAPI document: 1.0.0-rc.4
 * Contact: api@pixop.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.pixop.api.sdk.model.dto;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonSubTypes;
import com.fasterxml.jackson.annotation.JsonTypeInfo;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import com.pixop.api.sdk.model.dto.AccountAdjustment;
import com.pixop.api.sdk.model.dto.Product;
import com.pixop.api.sdk.model.dto.Transaction;
import com.pixop.api.sdk.model.dto.TransactionType;
import java.math.BigDecimal;
import java.time.OffsetDateTime;
import java.util.UUID;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;
import java.io.UnsupportedEncodingException;
import java.net.URLEncoder;
import java.util.StringJoiner;

/**
 * A transaction related to utilities, such as downloads or storage.
 */
@JsonPropertyOrder({
  UtilitiesTransaction.JSON_PROPERTY_PRODUCT
})
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2025-10-02T08:04:39.260621056Z[UTC]", comments = "Generator version: 7.15.0")
@JsonIgnoreProperties(
  value = "type", // ignore manually set type, it will be automatically generated by Jackson during serialization
  allowSetters = true // allows the type to be set during deserialization
)
@JsonTypeInfo(use = JsonTypeInfo.Id.NAME, include = JsonTypeInfo.As.PROPERTY, property = "type", visible = true)

public class UtilitiesTransaction extends Transaction {
  public static final String JSON_PROPERTY_PRODUCT = "product";
  @javax.annotation.Nullable
  private Product product;

  public UtilitiesTransaction() {

  }
  /**
   * Constructor with only readonly parameters
   */
  @JsonCreator
  public UtilitiesTransaction(
    @JsonProperty(JSON_PROPERTY_PRODUCT) Product product
  ) {
    this();
    this.product = product;
  }

  /**
   * The product associated with the utilities transaction.
   * @return product
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_PRODUCT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Product getProduct() {
    return product;
  }



  @Override
  public UtilitiesTransaction createdAt(@javax.annotation.Nonnull OffsetDateTime createdAt) {
    this.setCreatedAt(createdAt);
    return this;
  }

  @Override
  public UtilitiesTransaction type(@javax.annotation.Nonnull TransactionType type) {
    this.setType(type);
    return this;
  }

  @Override
  public UtilitiesTransaction amountUsd(@javax.annotation.Nonnull BigDecimal amountUsd) {
    this.setAmountUsd(amountUsd);
    return this;
  }

  @Override
  public UtilitiesTransaction balanceUsd(@javax.annotation.Nonnull BigDecimal balanceUsd) {
    this.setBalanceUsd(balanceUsd);
    return this;
  }

  @Override
  public UtilitiesTransaction videoId(@javax.annotation.Nullable UUID videoId) {
    this.setVideoId(videoId);
    return this;
  }

  @Override
  public UtilitiesTransaction accountAdjustment(@javax.annotation.Nullable AccountAdjustment accountAdjustment) {
    this.setAccountAdjustment(accountAdjustment);
    return this;
  }

  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    UtilitiesTransaction utilitiesTransaction = (UtilitiesTransaction) o;
    return Objects.equals(this.product, utilitiesTransaction.product) &&
        super.equals(o);
  }

  @Override
  public int hashCode() {
    return Objects.hash(product, super.hashCode());
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class UtilitiesTransaction {\n");
    sb.append("    ").append(toIndentedString(super.toString())).append("\n");
    sb.append("    product: ").append(toIndentedString(product)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

  /**
   * Convert the instance into URL query string.
   *
   * @return URL query string
   */
  public String toUrlQueryString() {
    return toUrlQueryString(null);
  }

  /**
   * Convert the instance into URL query string.
   *
   * @param prefix prefix of the query string
   * @return URL query string
   */
  public String toUrlQueryString(String prefix) {
    String suffix = "";
    String containerSuffix = "";
    String containerPrefix = "";
    if (prefix == null) {
      // style=form, explode=true, e.g. /pet?name=cat&type=manx
      prefix = "";
    } else {
      // deepObject style e.g. /pet?id[name]=cat&id[type]=manx
      prefix = prefix + "[";
      suffix = "]";
      containerSuffix = "]";
      containerPrefix = "[";
    }

    StringJoiner joiner = new StringJoiner("&");

    // add `createdAt` to the URL query string
    if (getCreatedAt() != null) {
      try {
        joiner.add(String.format("%screatedAt%s=%s", prefix, suffix, URLEncoder.encode(String.valueOf(getCreatedAt()), "UTF-8").replaceAll("\\+", "%20")));
      } catch (UnsupportedEncodingException e) {
        // Should never happen, UTF-8 is always supported
        throw new RuntimeException(e);
      }
    }

    // add `type` to the URL query string
    if (getType() != null) {
      try {
        joiner.add(String.format("%stype%s=%s", prefix, suffix, URLEncoder.encode(String.valueOf(getType()), "UTF-8").replaceAll("\\+", "%20")));
      } catch (UnsupportedEncodingException e) {
        // Should never happen, UTF-8 is always supported
        throw new RuntimeException(e);
      }
    }

    // add `amountUsd` to the URL query string
    if (getAmountUsd() != null) {
      try {
        joiner.add(String.format("%samountUsd%s=%s", prefix, suffix, URLEncoder.encode(String.valueOf(getAmountUsd()), "UTF-8").replaceAll("\\+", "%20")));
      } catch (UnsupportedEncodingException e) {
        // Should never happen, UTF-8 is always supported
        throw new RuntimeException(e);
      }
    }

    // add `balanceUsd` to the URL query string
    if (getBalanceUsd() != null) {
      try {
        joiner.add(String.format("%sbalanceUsd%s=%s", prefix, suffix, URLEncoder.encode(String.valueOf(getBalanceUsd()), "UTF-8").replaceAll("\\+", "%20")));
      } catch (UnsupportedEncodingException e) {
        // Should never happen, UTF-8 is always supported
        throw new RuntimeException(e);
      }
    }

    // add `videoId` to the URL query string
    if (getVideoId() != null) {
      try {
        joiner.add(String.format("%svideoId%s=%s", prefix, suffix, URLEncoder.encode(String.valueOf(getVideoId()), "UTF-8").replaceAll("\\+", "%20")));
      } catch (UnsupportedEncodingException e) {
        // Should never happen, UTF-8 is always supported
        throw new RuntimeException(e);
      }
    }

    // add `accountAdjustment` to the URL query string
    if (getAccountAdjustment() != null) {
      joiner.add(getAccountAdjustment().toUrlQueryString(prefix + "accountAdjustment" + suffix));
    }

    // add `product` to the URL query string
    if (getProduct() != null) {
      joiner.add(getProduct().toUrlQueryString(prefix + "product" + suffix));
    }

    return joiner.toString();
  }

}

