/*
 * Pixop API
 *  The Pixop API provides a comprehensive RESTful interface for interacting with the Pixop Platform. It allows users to manage API keys, projects, videos, and more.  The Pixop Platform offers video processing features such as upscaling, format conversion, and compression. It uses AI-driven algorithms to optimize video quality, reduce file sizes, and improve playback performance.  **Quick Start Guide** - Explore the [Pixop API Documentation](https://docs.pixop.com/reference/) to familiarize yourself with the API's capabilities.  **Required Headers** Include the following headers in all API requests: - `Accept`: `application/json` - `Content-Type`: `application/json` - `X-API-Key`: Your API key for authentication (e.g., `X-API-Key: <your-api-key>`).     **Note:** API key management endpoints that use Basic Authentication do not require the `X-API-Key` header.  **Rate Limits** All endpoints, except those related to API key management, enforce rate limits. Response headers provide the following rate limit details: - `X-RateLimit-Limit`: The maximum number of requests allowed per minute. - `X-RateLimit-Remaining`: The number of requests remaining in the current rate limit window. - `X-RateLimit-Reset`: The number of seconds until the current rate limit window resets. 
 *
 * The version of the OpenAPI document: 1.0.0-rc.5
 * Contact: api@pixop.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.pixop.api.sdk.model.dto;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.math.BigDecimal;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;
import java.io.UnsupportedEncodingException;
import java.net.URLEncoder;
import java.util.StringJoiner;

/**
 * Defines the normalized coordinates for cropping when &#x60;filters.reshaper&#x60; is set to &#x60;CROP&#x60;.  Coordinates are relative to the video dimensions. 
 */
@JsonPropertyOrder({
  VideoProcessingConfigurationOptionsFilterSettingsNormalizedCropCoordinates.JSON_PROPERTY_X1,
  VideoProcessingConfigurationOptionsFilterSettingsNormalizedCropCoordinates.JSON_PROPERTY_Y1,
  VideoProcessingConfigurationOptionsFilterSettingsNormalizedCropCoordinates.JSON_PROPERTY_X2,
  VideoProcessingConfigurationOptionsFilterSettingsNormalizedCropCoordinates.JSON_PROPERTY_Y2
})
@JsonTypeName("VideoProcessingConfigurationOptions_filterSettings_normalizedCropCoordinates")
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2025-10-07T11:16:38.307086065Z[UTC]", comments = "Generator version: 7.15.0")
public class VideoProcessingConfigurationOptionsFilterSettingsNormalizedCropCoordinates {
  public static final String JSON_PROPERTY_X1 = "x1";
  @javax.annotation.Nonnull
  private BigDecimal x1;

  public static final String JSON_PROPERTY_Y1 = "y1";
  @javax.annotation.Nonnull
  private BigDecimal y1;

  public static final String JSON_PROPERTY_X2 = "x2";
  @javax.annotation.Nonnull
  private BigDecimal x2;

  public static final String JSON_PROPERTY_Y2 = "y2";
  @javax.annotation.Nonnull
  private BigDecimal y2;

  public VideoProcessingConfigurationOptionsFilterSettingsNormalizedCropCoordinates() {
  }

  public VideoProcessingConfigurationOptionsFilterSettingsNormalizedCropCoordinates x1(@javax.annotation.Nonnull BigDecimal x1) {
    
    this.x1 = x1;
    return this;
  }

  /**
   * X-coordinate of the top-left corner.
   * minimum: 0
   * maximum: 1
   * @return x1
   */
  @javax.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_X1)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public BigDecimal getX1() {
    return x1;
  }


  @JsonProperty(JSON_PROPERTY_X1)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setX1(@javax.annotation.Nonnull BigDecimal x1) {
    this.x1 = x1;
  }

  public VideoProcessingConfigurationOptionsFilterSettingsNormalizedCropCoordinates y1(@javax.annotation.Nonnull BigDecimal y1) {
    
    this.y1 = y1;
    return this;
  }

  /**
   * Y-coordinate of the top-left corner.
   * minimum: 0
   * maximum: 1
   * @return y1
   */
  @javax.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_Y1)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public BigDecimal getY1() {
    return y1;
  }


  @JsonProperty(JSON_PROPERTY_Y1)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setY1(@javax.annotation.Nonnull BigDecimal y1) {
    this.y1 = y1;
  }

  public VideoProcessingConfigurationOptionsFilterSettingsNormalizedCropCoordinates x2(@javax.annotation.Nonnull BigDecimal x2) {
    
    this.x2 = x2;
    return this;
  }

  /**
   * X-coordinate of the bottom-right corner.
   * minimum: 0
   * maximum: 1
   * @return x2
   */
  @javax.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_X2)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public BigDecimal getX2() {
    return x2;
  }


  @JsonProperty(JSON_PROPERTY_X2)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setX2(@javax.annotation.Nonnull BigDecimal x2) {
    this.x2 = x2;
  }

  public VideoProcessingConfigurationOptionsFilterSettingsNormalizedCropCoordinates y2(@javax.annotation.Nonnull BigDecimal y2) {
    
    this.y2 = y2;
    return this;
  }

  /**
   * Y-coordinate of the bottom-right corner.
   * minimum: 0
   * maximum: 1
   * @return y2
   */
  @javax.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_Y2)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public BigDecimal getY2() {
    return y2;
  }


  @JsonProperty(JSON_PROPERTY_Y2)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setY2(@javax.annotation.Nonnull BigDecimal y2) {
    this.y2 = y2;
  }

  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    VideoProcessingConfigurationOptionsFilterSettingsNormalizedCropCoordinates videoProcessingConfigurationOptionsFilterSettingsNormalizedCropCoordinates = (VideoProcessingConfigurationOptionsFilterSettingsNormalizedCropCoordinates) o;
    return Objects.equals(this.x1, videoProcessingConfigurationOptionsFilterSettingsNormalizedCropCoordinates.x1) &&
        Objects.equals(this.y1, videoProcessingConfigurationOptionsFilterSettingsNormalizedCropCoordinates.y1) &&
        Objects.equals(this.x2, videoProcessingConfigurationOptionsFilterSettingsNormalizedCropCoordinates.x2) &&
        Objects.equals(this.y2, videoProcessingConfigurationOptionsFilterSettingsNormalizedCropCoordinates.y2);
  }

  @Override
  public int hashCode() {
    return Objects.hash(x1, y1, x2, y2);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class VideoProcessingConfigurationOptionsFilterSettingsNormalizedCropCoordinates {\n");
    sb.append("    x1: ").append(toIndentedString(x1)).append("\n");
    sb.append("    y1: ").append(toIndentedString(y1)).append("\n");
    sb.append("    x2: ").append(toIndentedString(x2)).append("\n");
    sb.append("    y2: ").append(toIndentedString(y2)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

  /**
   * Convert the instance into URL query string.
   *
   * @return URL query string
   */
  public String toUrlQueryString() {
    return toUrlQueryString(null);
  }

  /**
   * Convert the instance into URL query string.
   *
   * @param prefix prefix of the query string
   * @return URL query string
   */
  public String toUrlQueryString(String prefix) {
    String suffix = "";
    String containerSuffix = "";
    String containerPrefix = "";
    if (prefix == null) {
      // style=form, explode=true, e.g. /pet?name=cat&type=manx
      prefix = "";
    } else {
      // deepObject style e.g. /pet?id[name]=cat&id[type]=manx
      prefix = prefix + "[";
      suffix = "]";
      containerSuffix = "]";
      containerPrefix = "[";
    }

    StringJoiner joiner = new StringJoiner("&");

    // add `x1` to the URL query string
    if (getX1() != null) {
      try {
        joiner.add(String.format("%sx1%s=%s", prefix, suffix, URLEncoder.encode(String.valueOf(getX1()), "UTF-8").replaceAll("\\+", "%20")));
      } catch (UnsupportedEncodingException e) {
        // Should never happen, UTF-8 is always supported
        throw new RuntimeException(e);
      }
    }

    // add `y1` to the URL query string
    if (getY1() != null) {
      try {
        joiner.add(String.format("%sy1%s=%s", prefix, suffix, URLEncoder.encode(String.valueOf(getY1()), "UTF-8").replaceAll("\\+", "%20")));
      } catch (UnsupportedEncodingException e) {
        // Should never happen, UTF-8 is always supported
        throw new RuntimeException(e);
      }
    }

    // add `x2` to the URL query string
    if (getX2() != null) {
      try {
        joiner.add(String.format("%sx2%s=%s", prefix, suffix, URLEncoder.encode(String.valueOf(getX2()), "UTF-8").replaceAll("\\+", "%20")));
      } catch (UnsupportedEncodingException e) {
        // Should never happen, UTF-8 is always supported
        throw new RuntimeException(e);
      }
    }

    // add `y2` to the URL query string
    if (getY2() != null) {
      try {
        joiner.add(String.format("%sy2%s=%s", prefix, suffix, URLEncoder.encode(String.valueOf(getY2()), "UTF-8").replaceAll("\\+", "%20")));
      } catch (UnsupportedEncodingException e) {
        // Should never happen, UTF-8 is always supported
        throw new RuntimeException(e);
      }
    }

    return joiner.toString();
  }

}

